### ISSUE TITLE
Update SSL certificate

### ISSUE THREAD

**Issue by takashi247** [takashi247/launch-inception-on-ec2#2]
- Currently, a self certificate is being used
- Replace the self certificate with a CA-signed certificate

**Comment by takashi247** [comment]
Need to configure Nginx to be able to access via HTTP

**Comment by dhanyacp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hanoibamboo68, @airkaikai, @01saeidsalehi, @zhouop0, @AndreaPinna, @Opiumuzl, @Ellie-grah23, @einsli, @lualar, @0xcryptodad, @dustinltran, @svija, @Demontf, @davidbehrend, @heritager, @sheepxux, @salaivv, @nibabadebababa, @fujitahisami, @WJC5197, @JFWooten4, @topherfrancis, @vkaff, @Liam-Patten, @Henrietta888, @mari48073, @BramBouma, @kashifjee007, @jerrywjh, @derogab, @gurtntan, @cryptochou, @yq60523, @gardenias, @OdomarTrindade, @RoseWuyitong, @Deus219, @rixhoffjavascript, @IamTemmy, @tierreinhk, @yuanhang-zhou, @EdoardoPizzorno, @Assios, @marcialuizzza, @ads-light1992, @BurkhalterY, @NgihtSKight, @permiumether, @andiz2, @kelchnerridge83

**Comment by dhanyacp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
IdrisAkintobi, @egoistzty, @r00tbr0, @yed1, @huang2fire, @scottgriv, @vfa-tunq, @ssstaoself, @lihuibng, @islandbitcoin, @bluealert, @jinbearlo, @sephsa, @rainmana, @john-h3, @0x1211, @mertdlkr, @hihihi175hihihi, @LarryRuane, @ginjikata98, @erfannsb, @annjers, @MasterixCZ, @hina1975, @AndrewGlorious, @ADS-tak0626, @cao7113, @supermetrolog, @PedroVillegasss, @ambarringer, @mozzamglori, @peinlcy, @ashyls, @janellelynette, @rafalio-cb, @chongliujia, @RoninGotham, @sbs950, @Foxtrot-Zulu, @a-god-of-death, @ScaleBitAudit, @prashantsharma98, @Nuclear-Donkey, @talhatanveer, @amanone, @negativefactorial, @Yadira-Ferrer, @tiagoGottardo, @Susanta0, @totnine

**Comment by dhanyacp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
